[build]
  publish = "."
  command = "echo 'No build command specified'"

# Enable Netlify Identity
[functions]
  node_bundler = "esbuild"

# Required redirects for Identity to work properly
[[redirects]]
  from = "/.netlify/identity"
  to = "https://jchathub.netlify.app/.netlify/identity"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/identity/*"
  to = "https://jchathub.netlify.app/.netlify/identity/:splat"
  status = 200
  force = true

# Important: Handle the Identity endpoints
[[redirects]]
  from = "/.netlify/functions/identity"
  to = "https://jchathub.netlify.app/.netlify/functions/identity"
  status = 200
  force = true

[[redirects]]
  from = "/.netlify/functions/identity/*"
  to = "https://jchathub.netlify.app/.netlify/functions/identity/:splat"
  status = 200
  force = true

# Catch-all for SPA routing (if you're using a single-page app)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "identity-credentials-get=(self \"https://accounts.google.com\")"

# Headers for Identity endpoints
[[headers]]
  for = "/.netlify/identity/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
